### PR TITLE
update yarn version

### PR DESCRIPTION
**Pull request by davidimoore**
The purpose of this PR is to update the yarn version specified in the package.json file

### CODE REVIEW

**Comment by gylaz** [comment]
LGTM, but looks like Circle doesn't have yarn `1.1.0` yet?

**Comment by davidimoore** [comment]
I wonder if requiring a yarn version is necessary?

**Comment by gylaz** [comment]
Do you mean removing it from the `engines` specifications?

**Comment by davidimoore** [comment]
for yarn, yeah...feels equivalent to mandating a bundler version.

**Pull request closed without merging**
