### PR TITLE
Change primary typeface

### PR DESCRIPTION
**Pull request by tysongach**
I find Lato—the current typeface used across the app—to be a tad too friendly and wobbly (the flow and alignment between characters is inconsistent); lacking structure. Given those characteristics, this makes text feel disjointed from the strong, hefty Hound logo. I also find Lato to be quite thin and hard to read sometimes.

I recently came across the [Tofino](http://tofino.losttype.com/) typeface and tried it out on the Hound app. I think improves readability, but also pairs really well with the Hound logo. Even better, we can remove a bunch of CSS that tweaked letter spacing because Tofino is better built.

**Note:** I only have a free trial/personal version of Tofino, which I used to try it out on the app. We’d need to purchase a commercial license which is a flat $80, and also add it as a webfont to the app (which is why I labeled this as a WIP).

---

**With Tofino:**

houndci com-home-tofino

### CODE REVIEW

**Comment by smharley** [comment]
Overall, this is a great change! I think the homepage needs a little more love though (which could definitely be done separately). The italic "Currently style checking" feels more out of place and the language names below are a bit more condensed and harder to read. I have a similar feeling with the "Why does style matter" headings, maybe the bold is just throwing me off? Maybe the caps keep the letter-spacing?

In the docs, it feels like the line-height could be increased - most noticeable with the list in your example.

**Comment by tysongach** [comment]
All good suggestions! I’ll do some tweaking. I do plan to do more work on the home page and others beyond the typeface change, which I think will go a long way in making it feel more honed-in.

**Comment by tysongach** [comment]
@smharley Tweaked:

localhost-5000- laptop with hidpi screen

**Comment by smharley** [comment]
Looking great!

**Comment by tysongach** [comment]
Thanks for the sharp eyes, @smharley!

**Comment by tysongach** [comment]
I’ve not yet purchased font and contacted them to make sure we’d get WOFF and/or WOFF2 font files for the web. We’ll also need to figure out where to host those. I don’t think it’d be great if we added those font files to this public repo.

**Comment by tysongach** [comment]
I received WOFF files from the font maker and have purchased the license. Need to figure out where to host the font files. Perhaps our thoughtbot S3 bucket?

**Comment by gylaz** [comment]
S3 would be a good place. I think there is a standard place somewhere where thoughtbot stores its marketing assets, maybe that's where this one should go?

**Comment by tysongach** [comment]
I’ve added the fonts to our `thoughtbot-fonts` S3 buckets, which is served up at `font.thoughtbot.com`. I’ve also removed the Google Fonts import. This should be ready for final review and testing. Is there any thing we need to check/do because the fonts are served from a different domain?

**Comment by gylaz** [comment]
If it looks good on staging, then good to merge.

**Pull request merged**
