### PR TITLE
Upgrade rails to 5.1.0 rc

### PR DESCRIPTION
**Pull request by teoljungberg**
This is a WIP to test out `rspec-rails` support for `rails` 5.1

### CODE REVIEW

**Comment by gylaz** [comment]
Seems like a pretty straight forward upgrade.

**Comment by gylaz** [comment]
We may want to use `webpacker` gem now instead of our current Webpack approach.

**Comment by teoljungberg** [comment]
@gylaz Interesting idea, what do you think abouy doing that in a follow up PR?

**Comment by gylaz** [comment]
@teoljungberg How's this going? Worth revisiting now that 5.1 is out?

**Comment by gylaz** [comment]
Closing this in favor of #1402. This one was difficult to rebase.

**Pull request closed without merging**
