### PR TITLE
Updated success copy

### PR DESCRIPTION
**Pull request by TomasBarry**

### CODE REVIEW

**Comment by gylaz** [comment]
While I love the theme, I think this one might be a bit confusing. @salbertson thoughts?

**Comment by hlpatrick93** [comment]
Sounds like a really nice idea!

**Comment by gylaz** [comment]
@TomasBarry Sorry it took this long to get back to it. We do love the idea of Hound messaging having character. We talked about it and had some concerns about `No bones to pick` being explanatory enough. We decided that `Smells good to me. Woof!` would be a better fit (a play on LGTM and goes nicely together with pending review message). If you're able to make that change, we can merge your PR. Otherwise, we can make the change ourselves.

**Comment by salbertson** [comment]
Thanks @TomasBarry!

**Comment by TomasBarry** [comment]
@gylaz, @salbertson - I've updated the PR based on your comments. Thanks for looking!

**Comment by gylaz** [comment]
Thank you, merged!

**Pull request merged**
