### PR TITLE
Fix css for home/_index for medium screen

### PR DESCRIPTION
**Pull request by yatish27**

### CODE REVIEW

**Comment by gylaz** [comment]
Thanks for opening a PR @yatish27. I don't quite understand why this change is necessary. Could you please explain?

**Comment by gylaz** [comment]
@smharley Any thoughts on this one?

**Comment by smharley** [comment]
👍 Seems fine to me, I'm not sure why it was how it was, but this change is good.

image

Looks like there were 2 `$small-screen` media queries, but one of them should have been `$medium-screen`. Not a huge change, but seems consistent with other styles on the page.

**Comment by gylaz** [comment]
Awesome, merged.

**Pull request merged**
