### PR TITLE
Add support for Cane Linter

### PR DESCRIPTION
**Pull request by brgaulin**
Hello Hound Team =)

My team uses [Cane](https://github.com/square/cane) which is similar to Rubocop and we wanted to share that linter with the HoundCI community( if it wants it ;) )

This is some really basic stuff and is a bit of a work in progress(still needs tests!)

But I was curious if there was any interest in adding Cane, or pushback against adding it(don't want too many linters, about to do a major refactor, etc.) and am seeking feedback on these things.

### CODE REVIEW

**Comment by teoljungberg** [comment]
Thanks for the PR/. I have never heard of Cane prior to this PR.

I would like to hear more about what the interest is around adding support for Cane before working more on this PR.

**Comment by brgaulin** [comment]
Sure Teo -

We chose cane over rubocop for its simplicity. We have used rubocop before
and since it is a very large project we spent a great deal of time tweaking
rubocop, failing builds, etc.

Eventually we gave up, took too much of our time :(. And then we saw Cane.
It is a very simple metric gatherer that does what we are looking for(this
project is beyond being saved by something like rubocop, it started in the
rails 2/3 days with a team of up to 17 devs mostly cowboy coders or new to
ruby)

So my own argument against it, is it does very few style things. It's
mostly a metric tool. But we use hound on other projects, figured why not
add this one ;)

If we don't want to add this upstream that is ok by me. It's a small case
that I don't mind just maintaining a fork, which is pretty much what we do
today.
On Wed, Mar 16, 2016 at 6:49 AM Teo Ljungberg <notifications@github.com>
wrote:

> Thanks for the PR/. I have never heard of Cane prior to this PR.
>
> I would like to hear more about what the interest is around adding support
> for Cane before working more on this PR.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/houndci/hound/pull/1105#issuecomment-197258367>
>
-- 
--
Brendan Gaulin

**Comment by thorncp** [comment]
@brgaulin Thanks for your efforts and for bringing Cane to our attention!

We're working to ensure our existing linters are stable and aren't adding support for new ones at this time. I'm closing this and we can re-visit it later if we decide to add Cane support.

**Comment by brgaulin** [comment]
👍

**Pull request closed without merging**
