### PR TITLE
WIP: Polish up repos page

### PR DESCRIPTION
**Pull request by jcmorrow**
The repos grouped by organization is merged and functional, but there is probably room for improvement of the UX on that page.

Card with suggestions:
https://trello.com/c/uTdmx2Ga
repos_page

### CODE REVIEW

**Comment by jcmorrow** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;uTdmx2Ga&#x2F;769-refine-repos-page-ux"> Refine repos page UX</a>

**Comment by jcmorrow** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;uTdmx2Ga&#x2F;769-refine-repos-page-ux"> Refine repos page UX</a>

**Comment by gylaz** [comment]
Screenshot? Did something change visually? Looks good codewise.

**Comment by jcmorrow** [comment]
@gylaz I'm thinking of leaving this open while we decide what else we might want to change visually?

**Comment by gylaz** [comment]
@jcmorrow What do you think about merging and deploying to production? Then we can continuously release as we make UI improvements.

**Comment by jcmorrow** [comment]
@gylaz I'm cool with that! Iteration!

**Pull request merged**
